### ISSUE TITLE
2024 TODO

### ISSUE THREAD

**Issue by jared321** [POptUS/template_repo#4]
- [x] Update this repo based on changes made to IBCDFO by Jeff
- [x] Update this repo based on what I have learned from setting up other projects with this scheme
- [x] Figure out rules for writing tests that are single functions rather than TestCase classes
- [x] Integrate sphinx into `tox.ini` in a subtle way so that potential contributors don’t feel that they have to use sphinx
- [x] Determine what new issues should make their way into IBCDFO

**Comment by jared321** [comment]
In IBCDFO, the root `tox.ini` was updated to include actions such as running `flake8` and `black`.  The original intent of that file, however, was just to merge coverage results from multiple sources into a single coverage report that works well with coveralls.

Adding `flake8` in this repo didn't seem natural, so I decided not to add it in for now.  Rather, I wrote a tool that will run `flake8` on all python code, whether in a python package or not, but in a targeted way.  In particular, it lets each python package test itself as it sees fit.  Note that this script can be used by developers directly as well as be run in CI.

**Comment by jared321** [comment]
The following tentative documentation/testing requirement has been formulated by @jmlarson1  and I

>  Examples shall be included as a part of the poptus documentation scheme.  In order to confirm that our examples are always working, they shall be integrated into test suites.  So that the examples are minimal, readable, and useful, it shall be acceptable for the examples to be written ``outside'' of the testing framework (e.g., written as standalone functions and no registering of individual tests with the test framework) and only provide the testing framework with simple pass/fail status.

> Such dual-purpose examples might be referred to as ``functional'' or ``smoke'' tests.

I have explored two solutions to test out this requirement - one implemented in `mytemplate_pypkg` and one implementing an external (to the package) example of `mytemplate2`.

`mytemplate_pypkg`
================
This design satisfies the requirement as written.  In particular
* The package contains `examples` folders/submodules that house files containing a single function.
* Each function runs an example
* The function can only use `assert` statements for testing.  If no assert raises an exception, then the function is communicating a PASS; otherwise, FAILURE.
* The example is built into the test suite by writing a dedicated `TestCase` class with a single test function that simply calls the example function.  If an assert is raised by the function `unittest` does catch it and reports a failure.

Pros
-----
* Examples are encapsulated with functionality that it uses and its test within the package.
* Example code can easily be included into Sphinx documentation so that users don't have to go to repo or clone repo to immediately see examples.  But they don't look immediately like an application (See Cons below).  This inclusion seems natural since, at the moment, the sphinx docs are packaged up with the package itself.
* Relatively simple to implement and maintain since tests are auto-discovered.

Cons
-----
* The example code is written as a function so that it can be wrapped in a unittest TestCase.  This might not be the actual way that users would write up their own application, which might be confusing or annoying.
* Strange to send people off to read the code in a package.  This seems to break encapsulation and the idea that people don't need to know how we implemented the contents of a package.

Mixed bag
----------
* If an example requires external dependencies that the package doesn't otherwise need, then we force users to install it when they install the package regardless of whether or not they will run the example.  That said, creating the Python installation should be pretty straightforward since pip will help them find out what they need all within a single installation.

`mytemplate2`
===========
This design is in the spirit of the requirement, but does not satisfy it as written since the examples are tested but not part of the package's test suite.  In particular,
* an `examples` folder is placed at the root of the repo,
* each example is a different python script in that folder that returns an error code of 0 to indicated PASS; 1, otherwise.
* I have a GitHub action that runs each example.

Pros
----
* Some might consider it nice that the examples are outside of the package.  For instance, this keeps the package smaller and simpler.  The examples are also essentially applications and it might make more sense to keep applications outside of packages.
* The examples look closer to what a user would likely write.
* Example code can easily be included into Sphinx documentation so that users don't have to go to repo or clone repo to immediately see examples.  This is a little uncomfortable because the documentation is presently packaged with the package, but is built using text outside of the package.
* This is potentially more compatible with providing examples written as python notebooks.  **TODO**: How could we create a GitHub action that automatically confirms that notebook is executing correctly and generating correct results?

Cons
-----
* We can run the example in CI to confirm that the example functions and that the functionality it uses is working as expected.  However, this test is outside the package's test suite and is not presently included in code coverage.
* Developing and checking this code is external to `tox`, which requires writing extra CI actions.

Mixed bag
-----------
* If an example requires external dependencies that the package doesn't have, then we allow the package to be slimmer and minimal.  However, users might get frustrated when they find out through error messages that they need to install additional packages when trying to run the examples.

**Comment by jared321** [comment]
Jeff and I reviewed the two cases and believe that moving the examples out of the package and into a folder in the repo is the way that we should go for IBCDFO.  I will keep both examples in place in `template_repo` for historical reasons and future reference.

**Comment by jared321** [comment]
**Some thoughts on documentation related to the above comments**

I no longer assume that it is correct or a good idea to always conceive of the documentation as part of the package.  For example, if **sphinx-based** documentation is hosted on the web then I would consider that as the main avenue for finding the documentation and **not** include sphinx docs in the package.  This makes sense specifically for those that install the package via PyPI.  In this way, we are free to include the docs in the repo outside of the package source folder with the idea that maintainers are responsible for using that infrastructure to build and publish the documentation on behalf of the community.

However, it is unfortunate as people might not look for the documentation for the version of the package that they installed, but rather assume that the latest version is valid for them.  Note that people can still use `pydoc` to get the exact inline code documentation for their installation, but the sphinx markup might decrease the readability of this.

That said, we should assume that some users will need local access to the full documentation as they, for example, travel.  At present, we would allow them to access prebuilt documentation through GitHub action artifacts.  However, this is not an obvious path to take.  Therefore, we should also allow users to build the full documentation from the clone.  At the moment, I  do not think that forcing them to use `tox` for this is acceptable.

Add in a README that mentions the `tox` option but that also states basic procedure?

**Comment by jared321** [comment]
Addressed in PR #5
